### ISSUE TITLE
bugfix: analytics-site is broken in Docker

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#1773]
### Description

![image](https://github.com/devflowinc/trieve/assets/32852291/cdc8c039-544b-44d6-b160-f51a655b015e)

Error is shown here when forwarded through nginx.

```
Error: <A> and 'use' router primitives can be only used inside a Route.
    at im (index-BAychSpP.js:1:25673)
    at Ah (index-BAychSpP.js:1:27412)
    at Eh (index-BAychSpP.js:1:27528)
    at _l (index-BAychSpP.js:1:27558)
    at $b (index-BAychSpP.js:1:149570)
    at index-BAychSpP.js:1:9013
    at oe (index-BAychSpP.js:1:3918)
    at F (index-BAychSpP.js:1:9006)
    at get children (index-BAychSpP.js:1:150338)
    at Object.fn (index-BAychSpP.js:1:7927)
```

Build docker image with 
`docker build -f analytics-site/Dockerfile . -t analytics`

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:matrix.zerodao.gg)

**Comment by skeptrunedev** [comment]
This error can also be replicated with: 

```
set -a && source .env && set +a
yarn build 
cp ./dist/index.html ./index.html.template
envsubst < index.html.template > dist/index.html && rm index.html.template
yarn preview
```
