### ISSUE TITLE
bugfix: zod error for chunks that have no metadata in analytics panels.

### ISSUE THREAD

**Issue by cdxker** [devflowinc/trieve#2524]
### Description

Reproducing steps:
1) Run the following script: 
```ts
import { TrieveSDK } from "trieve-ts-sdk";

export const trieve = new TrieveSDK({
  baseUrl: "http://localhost:8090",
  apiKey: "tr-ssj0vubW4ZKV4A6QPT0Vca1xu9BOoBhc",
  datasetId: "15f99c05-661f-48cf-8102-aa3a0a86a43a"
});

const data = await trieve.createChunk({
  chunk_html: "hoi"
})
```

2) Perform a search in the search UI

3) View the analytics for the search

This error appears in the console, and the UI doesn't finish rendering.

```
ZodError
    at get error (zod.js?v=d3e709fe:509:23)
    at Object.fn (ResultCard.tsx:27:33)
    at runComputation (chunk-U2ZEA3QN.js?v=d3e709fe:748:22)
    at updateComputation (chunk-U2ZEA3QN.js?v=d3e709fe:727:3)
    at createMemo (chunk-U2ZEA3QN.js?v=d3e709fe:253:10)
    at _$$component.location (ResultCard.tsx:20:20)
    at @solid-refresh:25:42
    at untrack (chunk-U2ZEA3QN.js?v=d3e709fe:472:12)
    at HMRComp.createMemo.name [as fn] (@solid-refresh:25:28)
    at runComputation (chunk-U2ZEA3QN.js?v=d3e709fe:748:22)
```

![image](https://github.com/user-attachments/assets/3cdb6150-f45c-4aaf-8908-b755a42e3bb2)

### Target(s)

`dashboard`

### Requirement to close

- [ ] No zod error should return for analytics chunks that have no metadata.

### Community channels

Matrix is preferred. Reach out on discord or Matrix for further assistance. 

- [discord](https://discord.gg/CuJVfgZf54)
- [matrix](https://matrix.to/#/#trieve-general:trieve.ai)

**Comment by drew-harris** [comment]
https://github.com/devflowinc/trieve/pull/2526
